gsb/Models/Metier/Praticien.cs
namespace gsb.Models.Metier
{
    public class Praticien
    {
        private int id_praticien;
        private string nom_praticien;
        private string prenom_praticien;
        private string adresse_praticien;
        private string cp_praticien;
        private string ville_praticien;
        private double coef_notoriete;

        public int Id_praticien { get => id_praticien; set => id_praticien = value; }
        public string Nom_praticien { get => nom_praticien; set => nom_praticien = value; }
        public string Prenom_praticien { get => prenom_praticien; set => prenom_praticien = value; }
        public string Adresse_praticien { get => adresse_praticien; set => adresse_praticien = value; }
        public string Cp_praticien { get => cp_praticien; set => cp_praticien = value; }
        public string Ville_praticien { get => ville_praticien; set => ville_praticien = value; }
        public double Coef_notoriete { get => coef_notoriete; set => coef_notoriete = value; }
    }
}

gsb/Controllers/PraticienController.cs
using Microsoft.AspNetCore.Mvc;
using gsb.Models.Dao;
using gsb.Models.MesExceptions;
using System;
using System.Data;
using gsb.Models.Metier;
using gsb.Models.Persistance;

namespace gsb.Controllers
{
    public class PraticienController : Controller
    {
        public IActionResult ListePraticien()
        {
            try
            {
                var mesPraticiens = ServicePraticien.GetTousLesPraticiens();
                return View(mesPraticiens);
            }
            catch (MonException e)
            {
                return StatusCode(418);
            }
        }



        // Méthode d'action pour afficher le formulaire de recherche de praticien 

        [HttpGet]
        public IActionResult RechercherPraticien()
        {
            return View("RechercherPraticien");
        }

        [HttpPost]
        public IActionResult RechercherParNom(string nomPraticien)
        {
            try
            {
                DataTable praticiens = ServicePraticien.RechercherParNomPraticien(nomPraticien);
                return PartialView("_DetailsPraticien", praticiens);
            }
            catch (MonException e)
            {
                return StatusCode(500);
            }
        }



        // pour  ajouter  une invitation 
        [HttpPost]
        [HttpPost]
        public IActionResult AjouterInvitation(Activite uneActivite, int id_praticien)
        {
            try
            {
                if (ModelState.IsValid && id_praticien > 0)
                {
                    // Ajout de l'activité et récupération de son ID
                    int idActiviteCompl = ServicePraticien.AjouterActivite(uneActivite.date_activite, uneActivite.lieu_activite, uneActivite.motif_activite, uneActivite.theme_activite);

                    // Vérifier si l'ajout de l'activité a réussi
                    if (idActiviteCompl > 0)
                    {
                        // Insertion de l'invitation en utilisant l'ID de l'activité et l'ID du praticien
                        ServicePraticien.InsertInvitation(new Invitation { Id_activite_compl = idActiviteCompl, Id_praticien = id_praticien });

                        return RedirectToAction("ListePraticien");
                    }
                    else
                    {
                        // Si l'ajout de l'activité a échoué, retourne la vue avec le modèle d'activité
                        ModelState.AddModelError(string.Empty, "Erreur lors de l'ajout de l'activité.");
                        return View(uneActivite);
                    }
                }
                else
                {
                    return View(uneActivite);
                }
            }
            catch (MonException e)
            {
                return StatusCode(500);
            }
        }







        [HttpGet]
        public IActionResult Modifier(int idInvitation)
        {
            try
            {
                var invitation = ServicePraticien.GetInvitation(idInvitation);

                if (invitation == null)
                {
                    return NotFound();
                }

                return View(invitation);
            }
            catch (MonException e)
            {
                return StatusCode(500);
            }
        }


        [HttpPost]
        public IActionResult Modifier(Invitation invitation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ServicePraticien.ModifierInvitation(invitation.Id_activite_compl, invitation.Specialiste);

                    return RedirectToAction("ListePraticien");
                }
                else
                {
                    return View(invitation);
                }
            }
            catch (MonException e)
            {
                return StatusCode(500);
            }
        }
    }
}

gsb/Views/Praticien/AjouterInvitation.cshtml
@model System.Data.DataTable

@{
    ViewBag.Title = "Ajouter une invitation";
    Layout = "~/Views/Shared/_layoutGsb.cshtml";
}

<h1>@ViewBag.Title</h1>

@if (Model != null)
{
    @using (Html.BeginForm("AjouterInvitation", "Praticien", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="card col-8 mx-auto mt-5">
            <div class="card-body">
                <h3 class="card-title">Ajouter une invitation</h3>
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                   

                    <div class="form-group">
                        <label for="date_activite">Date de l'activité :</label>
                        <input type="date" class="form-control" id="date_activite" name="date_activite" />
                    </div>

                    <div class="form-group">
                        <label for="lieu_activite">Lieu de l'activité :</label>
                        <input type="text" class="form-control" id="lieu_activite" name="lieu_activite" />
                    </div>

                    <div class="form-group">
                        <label for="theme_activite">Thème de l'activité :</label>
                        <input type="text" class="form-control" id="theme_activite" name="theme_activite" />
                    </div>

                    <div class="form-group">
                        <label for="motif_activite">Motif de l'activité :</label>
                        <input type="text" class="form-control" id="motif_activite" name="motif_activite" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Enregistrer" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    }
}

gsb/Views/Praticien/Modifier.cshtml
@model gsb.Models.Metier.Invitation

@{
    ViewBag.Title = "Modifier une invitation";
    Layout = "~/Views/Shared/_layoutGsb.cshtml";
}

<h1>@ViewBag.Title</h1>

@if (Model != null)
{
    @using (Html.BeginForm("Modifier", "Praticien", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="card col-8 mx-auto mt-5">
            <div class="card-body">
                <h3 class="card-title">Modifier une invitation</h3>
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label for="id_praticien">Praticien :</label>
                        <input type="hidden" name="id_praticien" value="@Model.Id_praticien" />
                        <input type="text" class="form-control" value="@Model.Id_praticien" disabled />
                    </div>
                    <div class="form-group">
                        <label for="id_activite_compl">Activité :</label>
                        <input type="hidden" name="id_activite_compl" value="@Model.Id_activite_compl" />
                        <input type="text" class="form-control" value="@Model.Id_activite_compl" disabled />
                    </div>
                    <div class="form-group">
                        <label for="specialiste">Spécialiste :</label>
                        <input name="specialiste" type="checkbox" class="form-control" id="specialiste" @(Model.Specialiste ? "checked" : "") />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Enregistrer" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    }
}

gsb/Views/Praticien/RechercherPraticien.cshtml
@model System.Data.DataTable
@using System.Data

@{
    ViewBag.Title = "Recherche par Nom de Praticien";
    Layout = "~/Views/Shared/_layoutGsb.cshtml";
}



<div class="container">
    <div class="col-md-8 col-sm-8">
        <div class="blanc">
            <h1>Recherche par Nom de Praticien</h1>
            <input type="text" id="nomPraticien" />
            <br /><br />
            <div id="detailsPraticien"></div>
            <br /><br />
            <div class="">
                <a href="/" class="btn btn-default btn-primary">Retourner à l'accueil</a>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#nomPraticien').on('input', function () {
            var nomPraticien = $(this).val();
            if (nomPraticien !== "") {
                $.ajax({
                    url: '@Url.Action("RechercherParNom", "Praticien")',
                    type: 'POST',
                    data: { nomPraticien: nomPraticien },
                    success: function (data) {
                        $('#detailsPraticien').html(data);
                    },
                    error: function () {
                        $('#detailsPraticien').html('<p>Une erreur s\'est produite lors de la récupération des détails du praticien.</p>');
                    }
                });
            } else {
                $('#detailsPraticien').empty();
            }
        });
    });
</script>

gsb/Views/Praticien/_DetailsPraticien.cshtml
@model System.Data.DataTable
@using System.Data

@if (Model != null && Model.Rows.Count > 0)
{
    <div class="container">
        <div class="col-md-8 col-sm-8">
            <div class="blanc">
                <h1>Détails du Praticien</h1>
                <table class="table table-bordered table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Motif de l'Activité</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow dataRow in Model.Rows)
                        {
                            <tr>
                                <td>@dataRow["nom_praticien"].ToString()</td>
                                <td>@dataRow["prenom_praticien"].ToString()</td>
                                <td>@dataRow["motif_activite"].ToString()</td>
                            </tr>
                        }
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
}
else
{
    <p>Aucun praticien trouvé avec ce nom.</p>
}

gsb/Views/Praticien/listePraticien.cshtml
@model System.Data.DataTable

@{
    ViewBag.Title = "Affichage d'un praticien";
    Layout = "~/Views/Shared/_layoutGsb.cshtml";
}

<div class="container">
    <div class="col-md-12">
        <div class="blanc">
            <h1>Liste des praticiens avec détails de l'invitation à une activité complémentaire</h1>
        </div>

        <table class="table table-bordered table-striped table-responsive">
            <thead>
                <tr>
                    <th>Nom Praticien</th>
                    <th>Prénom Praticien</th>
                    <th>Date Activité</th>
                    <th>Lieu Activité</th>
                    <th>Thème Activité</th>
                    <th>Motif Activité</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Rows.Count > 0)
                {
                    @foreach (System.Data.DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@row["nom_praticien"]</td>
                            <td>@row["prenom_praticien"]</td>
                            <td>@row["date_activite"]</td>
                            <td>@row["lieu_activite"]</td>
                            <td>@row["theme_activite"]</td>
                            <td>@row["motif_activite"]</td>
                            <td>
                                <a href="/Praticien/AjouterInvitation?idPraticien=@row["id_praticien"]" class="btn btn-primary"><i class="bi bi-plus"></i> Ajouter</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="7">Aucun praticien trouvé.</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>